# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Deploy Express App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3                     # клонирует источник на runner, но не копирует на сервер
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies (локально - опционально)
      run: npm ci
    - name: Update and deploy code on server via git pull
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        script: |
          cd /home/${{ secrets.SERVER_USER }}/express-app      # путь до локального клона репозитория на сервере
          git reset --hard                                      # сбрасываем локальные изменения (будьте осторожны!)
          git pull origin main                                  # тянем последние изменения
          npm install                                          # обновляем зависимости, если есть
          pm2 reload my-express-app || pm2 start app.js --name my-express-app

